### 이동 여정 수정 성공
PATCH http://localhost:8080/trips/2/transport/7
Content-Type: application/json

{
  "name": "강남역으로 이동",
  "transportation": "버스",
  "departure_location": "서울역",
  "departure_address": "서울특별시 용산구 한강대로 지하392 (동자동)",
  "arrival_location": "강남역",
  "arrival_address": "서울특별시 강남구 강남대로 328 (역삼동)",
  "departure_date_time": "2023-12-11T12:30:00",
  "arrival_date_time": "2023-12-14T13:30:00"
}

### 숙박 여정 수정 성공
PATCH http://localhost:8080/trips/2/accommodation/3
Content-Type: application/json

{
  "accommodation_name": "가나호텔",
  "type": "accommodation"
}

### 체류 여정 수정 성공
PATCH http://localhost:8080/trips/2/stay/7
Content-Type: application/json

{
  "name": "남산 케이블카 타기",
  "type": "stay"
}