### 여행 수정 성공
PATCH http://localhost:8080/trips/2
Content-Type: application/json

{
  "name": "근교 여행",
  "start_date": "2023-12-20",
  "end_date": "2023-12-23",
  "is_domestic": true
}

### 여행 수정 성공
PATCH http://localhost:8080/trips/6
Content-Type: application/json

{
  "name": "부산 여행",
  "start_date": "2023-12-25",
  "end_date": "2023-12-26",
  "is_domestic": false
}