### 이동 여정 생성 성공
POST http://localhost:8080/trips/2/transport
Content-Type: application/json

{
  "name": "강남으로 이동",
  "transportation": "지하철",
  "departure_location": "서울역",
  "arrival_location": "강남",
  "departure_date_time": "2023-12-21T11:00:00",
  "arrival_date_time": "2023-12-22T12:00:00",
  "type": "transport"
}

### 숙박 여정 생성 성공
POST http://localhost:8080/trips/2/itinerary
Content-Type: application/json

{
  "name": "신라호텔 1박",
  "accommodation_name": "신라호텔",
  "check_in_time": "2023-12-25T19:00:00",
  "check_out_time": "2023-12-26T11:00:00",
  "type": "accommodation"
}

### 체류 여정 생성 성공
POST http://localhost:8080/trips/2/itinerary
Content-Type: application/json

{
  "name": "남산 타워 구경",
  "location": "남산",
  "arrival_date_time": "2023-12-26T12:00:00",
  "leave_date_time": "2023-12-26T15:00:00",
  "type": "stay"
}